### ISSUE TITLE
[Bug] RuntimeException: PersistentEnumerator storage corrupted

### ISSUE THREAD

**Issue by CrosMG** [magento/magento2-phpstorm-plugin#741] opened 2021-11-09 11:35 UTC
**Describe the bug** (*)

```
java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/ishcherbyna/.cache/JetBrains/PhpStorm2021.2/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSConnection.handleError(PersistentFSConnection.java:291)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.handleError(FSRecords.java:717)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:251)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getNameId(FSRecords.java:499)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findExistingChildInfo(PersistentFSImpl.java:444)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$findChildInfo$4(PersistentFSImpl.java:395)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:302)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:432)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:537)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:56)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:59)
	at com.intellij.lang.typescript.library.download.TypeScriptDefinitionFilesDirectory.getGlobalTypesDirectory(TypeScriptDefinitionFilesDirectory.java:41)
	at com.intellij.lang.javascript.library.JSLibraryMappings.getLibraryScopeForFileWithoutPredefined(JSLibraryMappings.java:109)
	at com.intellij.lang.javascript.psi.resolve.JSResolveScopeProvider.getProjectAndLibrariesScope(JSResolveScopeProvider.java:56)
	at com.intellij.lang.javascript.psi.resolve.JavaScriptResolveScopeProvider.getProjectAndLibrariesScope(JavaScriptResolveScopeProvider.java:57)
	at com.intellij.lang.javascript.psi.resolve.JavaScriptResolveScopeProvider.getResolveScope(JavaScriptResolveScopeProvider.java:49)
	at com.intellij.lang.javascript.flow.FlowJSResolveScopeProvider.getResolveScope(FlowJSResolveScopeProvider.java:35)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.createScopeByFile(ResolveScopeManagerImpl.java:70)
	at com.intellij.util.containers.ConcurrentFactoryMap$3.create(ConcurrentFactoryMap.java:184)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getResolveScopeFromProviders(ResolveScopeManagerImpl.java:88)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getDefaultResolveScope(ResolveScopeManagerImpl.java:166)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.getResolveScope(JSResolveUtil.java:485)
	at com.intellij.lang.javascript.psi.impl.JSStubElementImpl.getResolveScope(JSStubElementImpl.java:258)
	at com.magento.idea.magento2plugin.reference.provider.RequireJsPreferenceReferenceProvider.getReferencesByElement(RequireJsPreferenceReferenceProvider.java:20)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:199)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:162)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:141)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:31)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.createRefs(JSLiteralExpressionImpl.java:103)
	at com.intellij.lang.javascript.psi.impl.JSLiteralExpressionImpl.lambda$static$0(JSLiteralExpressionImpl.java:78)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:46)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intell
```

**To Reproduce** (*)

**Expected behavior** (*)

**Screenshots**

**Please complete the following information:** (*)

 - OS: Linux 4.15.0-162-generic
 - PhpStorm/Intellij version: 2021.2.3
 - Plugin Version: 4.0.0

**Additional context**

**Comment by bohdan-harniuk** [comment] 2021-12-01 11:11
Hello, @CrosMG !
Thank you for your report!

We will try to fix this issue in the next bug-fix release.
Could you please provide some additional information about this exception? Maybe you know the file that caused this exception?

Thanks, 
Bohdan

**Comment by bohdan-harniuk** [comment] 2021-12-13 16:38
Hello, @CrosMG!

I am waiting for your reply. I cannot proceed with the fixing without your assisting.

Thank you in advance!

**Comment by bohdan-harniuk** [comment] 2022-01-23 13:20
Hello, @CrosMG!

I am closing this issue due to inability to reproduce.
If you will face this issue again, please, reopen this issue and add steps to reproduce.

Regards,

**Closed by bohdan-harniuk** 2022-01-23 13:20 UTC
Labels: bug, question, not reproducible
