### ISSUE TITLE
Cannot use New - Module File - Cron

### ISSUE THREAD

**Issue by thejimu** [magento/magento2-phpstorm-plugin#397] opened 2020-11-18 06:47 UTC
**Describe the bug** (*) 

When using project short cut to create a cron, after entering cron details into the dialog the response will either be a) nothing or b) an error - if using a config path for the cron schedule.

**To Reproduce** (*) 

1. Right click on your module folder
2. Navigate to new
3. Navigate to Magento Module File context menu
4. Select Cron
5. Enter in Cron details
6. Clock OK

**Expected behavior** (*) 

Cron class and XML file should be created

**Screenshots**

**Please complete the following information:** (*) 

 - OS: MacOS 10.15.6
 - PhpStorm/Intellij version: 2020.2.3
 - Plugin Version: 2.0.2

**Additional context**

**Comment by drpayyne** [comment] 2020-11-20 17:11
Hi @thejimu, thanks for reporting the bug, but I'm unable to reproduce it. Could you please add some screenshots of the error and the data you're inputting? Maybe that could help us reproduce it and narrow down the cause. Thank you!

**Comment by VitaliyBoyko** [comment] 2021-01-25 15:30
Closing as non reproducible

**Closed by VitaliyBoyko** 2021-01-25 15:30 UTC
Labels: bug, not reproducible
