### ISSUE TITLE
Try create new Magento 2 CLI Command

### ISSUE THREAD

**Issue by tinhnd2** [magento/magento2-phpstorm-plugin#520] opened 2021-03-30 04:11 UTC
**Describe the bug** (*) 

When I try to create new command the plugin throws a missing description field.

**To Reproduce** (*) 

1. Open PHP Storm with Magento project
2. Click New -> Module files -> Magento 2 CLI Command
3. Enter info
4. See an error: missing description field

**Screenshots**

**Please complete the following information:** (*) 

 - OS: Ubuntu 20.04
 - PhpStorm/Intellij version: 2020.3.2
 - Plugin Version: 3.1.3

![2021-03-30_11-04](https://user-images.githubusercontent.com/79310184/112932673-85006300-9148-11eb-8bae-36cbc33a9be0.png)

Please fix this bug.

**Comment by VitaliyBoyko** [comment] 2021-03-30 13:17
Weird, on a Mac it's ok 🤔 
<img width="398" alt="Screenshot 2021-03-30 at 16 16 51" src="https://user-images.githubusercontent.com/20116393/112994862-5b106600-9173-11eb-920d-2bbe9cf76f15.png">

**Comment by eduard13** [comment] 2021-03-30 13:39
@VitaliyBoyko, I believe the question/issue here, is why the description is a required field. `\Symfony\Component\Console\Command\Command::$description` defaults to empty string, which means the description may be empty. But I might be wrong and the reporter reported some other issue.

Thanks.

**Comment by tinhnd2** [comment] 2021-04-02 06:09
Hi @eduard13
I mean the description field is disappear in my Editor.
Yep, the description field requires related to my issues.
Thanks.

**Comment by eduard13** [comment] 2021-04-02 06:20
@tinhnd2 unfortunately, I don't have an Ubuntu OS to test it on my side, however do you have the same behavior even after closing and re-opening this dialog again?

**Comment by dylanngo95** [comment] 2021-04-03 03:02
@eduard13  There is my editor screenshot:
![2021-04-03_10-01](https://user-images.githubusercontent.com/11944757/113466159-bd16e700-9463-11eb-8732-80794a6189dd.png)
Thanks

**Comment by ProkopovVitaliy** [comment] 2021-04-13 16:24
@dylanngo95 Thank you for report. 

I checked described issue on ubuntu but for me it's work fine and text area looks ok.
![Screenshot from 2021-04-13 15-56-14](https://user-images.githubusercontent.com/29776509/114586267-26c99900-9c8d-11eb-97ef-9efa2d2067d3.png)

But i notice you are using some custom theme. I can guess this theme can be reason of this issue. Can you turn on default one, for example  "Darcula" , and try to reproduce this issue again? 

Thanks!

**Comment by VitaliyBoyko** [comment] 2021-04-13 18:12
Looks like the issue related to the custom theme neither to the OS nor plugin. Closing this one though.

**Closed by VitaliyBoyko** 2021-04-13 18:12 UTC
Labels: bug
