### ISSUE TITLE
Line markers. Fix performance warnings

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#31] opened 2020-03-04 20:55 UTC
We have the following warning on the plugins and WEB API line markets:
![image](https://user-images.githubusercontent.com/20116393/75922032-e7fec800-5e6a-11ea-844d-720c86ed3462.png)

The issue could be fixed using `PsiTreeUtil.getDeepestFirst(psiElement)` or `PsiTreeUtil.getDeepestLast(psiElement)` function (`com.intellij.psi.util.PsiTreeUtil`).

**Comment by rogyar** [comment] 2020-03-25 08:09
I will handle it

**Comment by rogyar** [comment] 2020-03-25 13:36
Fortunately, we're not able to reproduce this issue. Please, feel free to close it.

**Comment by VitaliyBoyko** [comment] 2020-03-25 13:40
@rogyar Thank you 🙏

**Comment by VitaliyBoyko** [comment] 2020-04-16 15:47
It seems to be still reproducible. I will recheck it.

**Closed** 2020-04-17 06:25 UTC
Labels: Award: bug fix, bug, good first issue, line marker, release-1.0.0
